// AUTO-GENERATED — ISO numeric <-> alpha2 <-> continent for FlagLocator map
// num = ISO 3166-1 numeric (matches world-atlas feature id). code = alpha-2 lowercase (DB + flagcdn).
export const COUNTRY_DATA = {
  'ad': { num: 20, cont: 'europe', name: 'Andorra' },
  'ae': { num: 784, cont: 'asia', name: 'United Arab Emirates' },
  'af': { num: 4, cont: 'asia', name: 'Afghanistan' },
  'ag': { num: 28, cont: 'central-americas', name: 'Antigua and Barbuda' },
  'al': { num: 8, cont: 'europe', name: 'Albania' },
  'am': { num: 51, cont: 'asia', name: 'Armenia' },
  'ao': { num: 24, cont: 'africa', name: 'Angola' },
  'ar': { num: 32, cont: 'south-americas', name: 'Argentina' },
  'at': { num: 40, cont: 'europe', name: 'Austria' },
  'au': { num: 36, cont: 'oceania', name: 'Australia' },
  'az': { num: 31, cont: 'asia', name: 'Azerbaijan' },
  'ba': { num: 70, cont: 'europe', name: 'Bosnia and Herzegovina' },
  'bb': { num: 52, cont: 'central-americas', name: 'Barbados' },
  'bd': { num: 50, cont: 'asia', name: 'Bangladesh' },
  'be': { num: 56, cont: 'europe', name: 'Belgium' },
  'bf': { num: 854, cont: 'africa', name: 'Burkina Faso' },
  'bg': { num: 100, cont: 'europe', name: 'Bulgaria' },
  'bh': { num: 48, cont: 'asia', name: 'Bahrain' },
  'bi': { num: 108, cont: 'africa', name: 'Burundi' },
  'bj': { num: 204, cont: 'africa', name: 'Benin' },
  'bn': { num: 96, cont: 'asia', name: 'Brunei Darussalam' },
  'bo': { num: 68, cont: 'south-americas', name: 'Bolivia, Plurinational State of' },
  'br': { num: 76, cont: 'south-americas', name: 'Brazil' },
  'bs': { num: 44, cont: 'central-americas', name: 'Bahamas' },
  'bt': { num: 64, cont: 'asia', name: 'Bhutan' },
  'bw': { num: 72, cont: 'africa', name: 'Botswana' },
  'by': { num: 112, cont: 'europe', name: 'Belarus' },
  'bz': { num: 84, cont: 'central-americas', name: 'Belize' },
  'ca': { num: 124, cont: 'north-americas', name: 'Canada' },
  'cd': { num: 180, cont: 'africa', name: 'Congo, The Democratic Republic of the' },
  'cf': { num: 140, cont: 'africa', name: 'Central African Republic' },
  'cg': { num: 178, cont: 'africa', name: 'Congo' },
  'ch': { num: 756, cont: 'europe', name: 'Switzerland' },
  'ci': { num: 384, cont: 'africa', name: 'Côte d\'Ivoire' },
  'cl': { num: 152, cont: 'south-americas', name: 'Chile' },
  'cm': { num: 120, cont: 'africa', name: 'Cameroon' },
  'cn': { num: 156, cont: 'asia', name: 'China' },
  'co': { num: 170, cont: 'south-americas', name: 'Colombia' },
  'cr': { num: 188, cont: 'central-americas', name: 'Costa Rica' },
  'cu': { num: 192, cont: 'central-americas', name: 'Cuba' },
  'cv': { num: 132, cont: 'africa', name: 'Cabo Verde' },
  'cy': { num: 196, cont: 'europe', name: 'Cyprus' },
  'cz': { num: 203, cont: 'europe', name: 'Czechia' },
  'de': { num: 276, cont: 'europe', name: 'Germany' },
  'dj': { num: 262, cont: 'africa', name: 'Djibouti' },
  'dk': { num: 208, cont: 'europe', name: 'Denmark' },
  'dm': { num: 212, cont: 'central-americas', name: 'Dominica' },
  'do': { num: 214, cont: 'central-americas', name: 'Dominican Republic' },
  'dz': { num: 12, cont: 'africa', name: 'Algeria' },
  'ec': { num: 218, cont: 'south-americas', name: 'Ecuador' },
  'ee': { num: 233, cont: 'europe', name: 'Estonia' },
  'eg': { num: 818, cont: 'africa', name: 'Egypt' },
  'er': { num: 232, cont: 'africa', name: 'Eritrea' },
  'es': { num: 724, cont: 'europe', name: 'Spain' },
  'et': { num: 231, cont: 'africa', name: 'Ethiopia' },
  'fi': { num: 246, cont: 'europe', name: 'Finland' },
  'fj': { num: 242, cont: 'oceania', name: 'Fiji' },
  'fm': { num: 583, cont: 'oceania', name: 'Micronesia, Federated States of' },
  'fr': { num: 250, cont: 'europe', name: 'France' },
  'ga': { num: 266, cont: 'africa', name: 'Gabon' },
  'gb': { num: 826, cont: 'europe', name: 'United Kingdom' },
  'gd': { num: 308, cont: 'central-americas', name: 'Grenada' },
  'ge': { num: 268, cont: 'asia', name: 'Georgia' },
  'gh': { num: 288, cont: 'africa', name: 'Ghana' },
  'gl': { num: 304, cont: 'north-americas', name: 'Greenland' },
  'gm': { num: 270, cont: 'africa', name: 'Gambia' },
  'gn': { num: 324, cont: 'africa', name: 'Guinea' },
  'gq': { num: 226, cont: 'africa', name: 'Equatorial Guinea' },
  'gr': { num: 300, cont: 'europe', name: 'Greece' },
  'gt': { num: 320, cont: 'central-americas', name: 'Guatemala' },
  'gw': { num: 624, cont: 'africa', name: 'Guinea-Bissau' },
  'gy': { num: 328, cont: 'south-americas', name: 'Guyana' },
  'hn': { num: 340, cont: 'central-americas', name: 'Honduras' },
  'hr': { num: 191, cont: 'europe', name: 'Croatia' },
  'ht': { num: 332, cont: 'central-americas', name: 'Haiti' },
  'hu': { num: 348, cont: 'europe', name: 'Hungary' },
  'id': { num: 360, cont: 'asia', name: 'Indonesia' },
  'ie': { num: 372, cont: 'europe', name: 'Ireland' },
  'il': { num: 376, cont: 'asia', name: 'Israel' },
  'in': { num: 356, cont: 'asia', name: 'India' },
  'iq': { num: 368, cont: 'asia', name: 'Iraq' },
  'ir': { num: 364, cont: 'asia', name: 'Iran, Islamic Republic of' },
  'is': { num: 352, cont: 'europe', name: 'Iceland' },
  'it': { num: 380, cont: 'europe', name: 'Italy' },
  'jm': { num: 388, cont: 'central-americas', name: 'Jamaica' },
  'jo': { num: 400, cont: 'asia', name: 'Jordan' },
  'jp': { num: 392, cont: 'asia', name: 'Japan' },
  'ke': { num: 404, cont: 'africa', name: 'Kenya' },
  'kg': { num: 417, cont: 'asia', name: 'Kyrgyzstan' },
  'kh': { num: 116, cont: 'asia', name: 'Cambodia' },
  'ki': { num: 296, cont: 'oceania', name: 'Kiribati' },
  'km': { num: 174, cont: 'africa', name: 'Comoros' },
  'kn': { num: 659, cont: 'central-americas', name: 'Saint Kitts and Nevis' },
  'kp': { num: 408, cont: 'asia', name: 'Korea, Democratic People\'s Republic of' },
  'kr': { num: 410, cont: 'asia', name: 'Korea, Republic of' },
  'kw': { num: 414, cont: 'asia', name: 'Kuwait' },
  'kz': { num: 398, cont: 'asia', name: 'Kazakhstan' },
  'la': { num: 418, cont: 'asia', name: 'Lao People\'s Democratic Republic' },
  'lb': { num: 422, cont: 'asia', name: 'Lebanon' },
  'lc': { num: 662, cont: 'central-americas', name: 'Saint Lucia' },
  'li': { num: 438, cont: 'europe', name: 'Liechtenstein' },
  'lk': { num: 144, cont: 'asia', name: 'Sri Lanka' },
  'lr': { num: 430, cont: 'africa', name: 'Liberia' },
  'ls': { num: 426, cont: 'africa', name: 'Lesotho' },
  'lt': { num: 440, cont: 'europe', name: 'Lithuania' },
  'lu': { num: 442, cont: 'europe', name: 'Luxembourg' },
  'lv': { num: 428, cont: 'europe', name: 'Latvia' },
  'ly': { num: 434, cont: 'africa', name: 'Libya' },
  'ma': { num: 504, cont: 'africa', name: 'Morocco' },
  'mc': { num: 492, cont: 'europe', name: 'Monaco' },
  'md': { num: 498, cont: 'europe', name: 'Moldova, Republic of' },
  'me': { num: 499, cont: 'europe', name: 'Montenegro' },
  'mg': { num: 450, cont: 'africa', name: 'Madagascar' },
  'mh': { num: 584, cont: 'oceania', name: 'Marshall Islands' },
  'mk': { num: 807, cont: 'europe', name: 'North Macedonia' },
  'ml': { num: 466, cont: 'africa', name: 'Mali' },
  'mm': { num: 104, cont: 'asia', name: 'Myanmar' },
  'mn': { num: 496, cont: 'asia', name: 'Mongolia' },
  'mr': { num: 478, cont: 'africa', name: 'Mauritania' },
  'mt': { num: 470, cont: 'europe', name: 'Malta' },
  'mu': { num: 480, cont: 'africa', name: 'Mauritius' },
  'mv': { num: 462, cont: 'asia', name: 'Maldives' },
  'mw': { num: 454, cont: 'africa', name: 'Malawi' },
  'mx': { num: 484, cont: 'north-americas', name: 'Mexico' },
  'my': { num: 458, cont: 'asia', name: 'Malaysia' },
  'mz': { num: 508, cont: 'africa', name: 'Mozambique' },
  'na': { num: 516, cont: 'africa', name: 'Namibia' },
  'ne': { num: 562, cont: 'africa', name: 'Niger' },
  'ng': { num: 566, cont: 'africa', name: 'Nigeria' },
  'ni': { num: 558, cont: 'central-americas', name: 'Nicaragua' },
  'nl': { num: 528, cont: 'europe', name: 'Netherlands' },
  'no': { num: 578, cont: 'europe', name: 'Norway' },
  'np': { num: 524, cont: 'asia', name: 'Nepal' },
  'nr': { num: 520, cont: 'oceania', name: 'Nauru' },
  'nz': { num: 554, cont: 'oceania', name: 'New Zealand' },
  'om': { num: 512, cont: 'asia', name: 'Oman' },
  'pa': { num: 591, cont: 'central-americas', name: 'Panama' },
  'pe': { num: 604, cont: 'south-americas', name: 'Peru' },
  'pg': { num: 598, cont: 'oceania', name: 'Papua New Guinea' },
  'ph': { num: 608, cont: 'asia', name: 'Philippines' },
  'pk': { num: 586, cont: 'asia', name: 'Pakistan' },
  'pl': { num: 616, cont: 'europe', name: 'Poland' },
  'ps': { num: 275, cont: 'asia', name: 'Palestine, State of' },
  'pt': { num: 620, cont: 'europe', name: 'Portugal' },
  'pw': { num: 585, cont: 'oceania', name: 'Palau' },
  'py': { num: 600, cont: 'south-americas', name: 'Paraguay' },
  'qa': { num: 634, cont: 'asia', name: 'Qatar' },
  'ro': { num: 642, cont: 'europe', name: 'Romania' },
  'rs': { num: 688, cont: 'europe', name: 'Serbia' },
  'ru': { num: 643, cont: 'europe', name: 'Russian Federation' },
  'rw': { num: 646, cont: 'africa', name: 'Rwanda' },
  'sa': { num: 682, cont: 'asia', name: 'Saudi Arabia' },
  'sb': { num: 90, cont: 'oceania', name: 'Solomon Islands' },
  'sc': { num: 690, cont: 'africa', name: 'Seychelles' },
  'sd': { num: 729, cont: 'africa', name: 'Sudan' },
  'se': { num: 752, cont: 'europe', name: 'Sweden' },
  'sg': { num: 702, cont: 'asia', name: 'Singapore' },
  'si': { num: 705, cont: 'europe', name: 'Slovenia' },
  'sk': { num: 703, cont: 'europe', name: 'Slovakia' },
  'sl': { num: 694, cont: 'africa', name: 'Sierra Leone' },
  'sm': { num: 674, cont: 'europe', name: 'San Marino' },
  'sn': { num: 686, cont: 'africa', name: 'Senegal' },
  'so': { num: 706, cont: 'africa', name: 'Somalia' },
  'sr': { num: 740, cont: 'south-americas', name: 'Suriname' },
  'ss': { num: 728, cont: 'africa', name: 'South Sudan' },
  'st': { num: 678, cont: 'africa', name: 'Sao Tome and Principe' },
  'sv': { num: 222, cont: 'central-americas', name: 'El Salvador' },
  'sy': { num: 760, cont: 'asia', name: 'Syrian Arab Republic' },
  'sz': { num: 748, cont: 'africa', name: 'Eswatini' },
  'td': { num: 148, cont: 'africa', name: 'Chad' },
  'tg': { num: 768, cont: 'africa', name: 'Togo' },
  'th': { num: 764, cont: 'asia', name: 'Thailand' },
  'tj': { num: 762, cont: 'asia', name: 'Tajikistan' },
  'tl': { num: 626, cont: 'asia', name: 'Timor-Leste' },
  'tm': { num: 795, cont: 'asia', name: 'Turkmenistan' },
  'tn': { num: 788, cont: 'africa', name: 'Tunisia' },
  'to': { num: 776, cont: 'oceania', name: 'Tonga' },
  'tr': { num: 792, cont: 'asia', name: 'Türkiye' },
  'tt': { num: 780, cont: 'central-americas', name: 'Trinidad and Tobago' },
  'tv': { num: 798, cont: 'oceania', name: 'Tuvalu' },
  'tw': { num: 158, cont: 'asia', name: 'Taiwan, Province of China' },
  'tz': { num: 834, cont: 'africa', name: 'Tanzania, United Republic of' },
  'ua': { num: 804, cont: 'europe', name: 'Ukraine' },
  'ug': { num: 800, cont: 'africa', name: 'Uganda' },
  'us': { num: 840, cont: 'north-americas', name: 'United States' },
  'uy': { num: 858, cont: 'south-americas', name: 'Uruguay' },
  'uz': { num: 860, cont: 'asia', name: 'Uzbekistan' },
  'va': { num: 336, cont: 'europe', name: 'Holy See (Vatican City State)' },
  'vc': { num: 670, cont: 'central-americas', name: 'Saint Vincent and the Grenadines' },
  've': { num: 862, cont: 'south-americas', name: 'Venezuela, Bolivarian Republic of' },
  'vn': { num: 704, cont: 'asia', name: 'Viet Nam' },
  'vu': { num: 548, cont: 'oceania', name: 'Vanuatu' },
  'ws': { num: 882, cont: 'oceania', name: 'Samoa' },
  'ye': { num: 887, cont: 'asia', name: 'Yemen' },
  'za': { num: 710, cont: 'africa', name: 'South Africa' },
  'zm': { num: 894, cont: 'africa', name: 'Zambia' },
  'zw': { num: 716, cont: 'africa', name: 'Zimbabwe' },
}

export const CONTINENTS = [
  { slug: 'europe', en: 'Europe', fr: 'Europe', count: 45 },
  { slug: 'africa', en: 'Africa', fr: 'Afrique', count: 54 },
  { slug: 'asia', en: 'Asia', fr: 'Asie', count: 48 },
  { slug: 'north-americas', en: 'North America', fr: 'Amérique du Nord', count: 4 },
  { slug: 'central-americas', en: 'Central America', fr: 'Amérique centrale', count: 20 },
  { slug: 'south-americas', en: 'South America', fr: 'Amérique du Sud', count: 12 },
  { slug: 'oceania', en: 'Oceania', fr: 'Océanie', count: 14 },
]

// numeric id -> alpha2 (for world-atlas feature lookup)
export const NUM_TO_CODE = Object.fromEntries(Object.entries(COUNTRY_DATA).map(([c, d]) => [d.num, c]))

export function codesForZone(zone) {
  if (zone === 'world') return Object.keys(COUNTRY_DATA)
  return Object.keys(COUNTRY_DATA).filter(c => COUNTRY_DATA[c].cont === zone)
}